from typing import Tuple, List
from sopy import Event

class eReadDirectory(Event[Tuple[str, List[str]]]): ...
class eFileCreated(Event[str | None]): ...

class eFileDeleteRequest(Event[str]): ...  # ToolUse message
class eFileDeleted(Event[str | None]): ... # ToolMessage

class eCopyRequest(Event[Tuple[str, str]]): ...
class eFileCopied(Event[Tuple[str, str] | None]): ...
